version: '3.8'

services:
  # Development frontend only
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PROXY_TARGET=http://host.docker.internal:8000
    network_mode: host

volumes: {}
networks: {}